Repository Code-the-Dream-School/ii-practicum-team-7-back, pull requests merged in 2025-04, with the labels that each got.

#9 Create pull_request_template.md
  .github/pull_request_template.md
Labels: Mentor Reviewed

#8 User Authentication
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/app.js
  src/config/connectDB.js
  src/controllers/user-auth.js
  src/db/connect.js
  src/errors/bad-request.js
  src/errors/custom-api.js
  src/errors/index.js
  src/errors/not-found.js
  src/errors/unauthenticated.js
  src/middleware/authentication.js
  src/middleware/not-found.js
  src/models/User.js
  src/routes/user-auth.js
  src/server.js
Labels: Peer Reviewed, Mentor Reviewed

#13 Scrum-62-backend-error-handling-and-Review-model
  src/app.js
  src/controllers/user-auth.js
  src/controllers/user-profile.js
  src/controllers/user-review.js
  src/errors/bad-request.js
  src/errors/index.js
  src/errors/unauthenticated.js
  src/middleware/authentication.js
  src/middleware/error-handler.js
  src/models/Profile.js
  src/models/Review.js
  src/models/User.js
  src/routes/reviewRoute.js
Labels: Peer Reviewed, Mentor Reviewed

#14 SCRUM-64-Job-model
  src/app.js
  src/controllers/jobs.js
  src/controllers/user-auth.js
  src/controllers/user-profile.js
  src/controllers/user-review.js
  src/models/Job.js
  src/routes/jobsRoute.js
Labels: Peer Reviewed, Mentor Reviewed

#15 SCRUM-71-add-o-auth-google-login-and-logout-be
  package-lock.json
  package.json
  src/app.js
  src/config/passport.js
  src/controllers/user-auth.js
  src/controllers/user-profile.js
  src/controllers/user-review.js
  src/errors/custom-api.js
  src/errors/index.js
  src/errors/not-found.js
  src/middleware/authentication.js
  src/middleware/not-found.js
  src/models/User.js
  src/routes/profile.js
  src/routes/profileRoute.js
  src/routes/reviewRoute.js
  src/routes/user-auth.js
  src/routes/userRoute.js
Labels: Mentor Reviewed, Ready for Review
